In [23]:
import pandas as pd
import sqlite3

In [24]:
departments = pd.read_csv('departments.csv')
employees = pd.read_csv('upd_empl_2.csv')
regions = pd.read_csv('regions.csv')

1. Un cliente llega a un mostrador cada 15 minutos en promedio. Si podemos modelar la llegada de clientes mediante
una **distribución exponencial**, ¿cuál es la probabilidad de esperar menos de 7 minutos entre clientes?

In [25]:
from scipy.stats import expon

# Lambda (tasa de llegada) es el inverso del tiempo promedio entre llegadas.
# Tiempo promedio entre llegadas = 15 minutos
# Lambda = 1 / 15 minutos = 1/15 clientes por minuto

lambd = 1/15

# Calculamos la probabilidad de esperar menos de 7 minutos
probability = expon.cdf(7, scale=1/lambd)

print(f"La probabilidad de esperar menos de 7 minutos entre clientes es: {probability}")

La probabilidad de esperar menos de 7 minutos entre clientes es: 0.3729109147269439

2. Considerando las tablas `employees`, `departments` y `regions`. Se utiliza sintaxis SQL para resolver lo siguiente:
- a) Obtener el número de empleados que hay por departamento pero considerando sólo los departamentos de 'Computers', 'Beauty' y 'Games' 
- b) Crear un query que usando joins entre las tablas devuelva los campos 'first_name', 'last_name', 'division','region' y 'country'.

In [30]:
#pip install ipython-sql
#!pip install pandasql

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: numpy in c:\users\kike2\anaconda3\lib\site-packages (from pandasql) (2.3.5)
Requirement already satisfied: pandas in c:\users\kike2\anaconda3\lib\site-packages (from pandasql) (2.3.3)
Requirement already satisfied: sqlalchemy in c:\users\kike2\anaconda3\lib\site-packages (from pandasql) (2.0.43)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kike2\anaconda3\lib\site-packages (from pandas->pandasql) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kike2\anaconda3\lib\site-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kike2\anaconda3\lib\site-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\kike2\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)
Requirement already satisfied: greenlet>=1 in c:\users\kike2\anaconda3\lib\site-packages (from sqlalchemy->pandasql) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\kike2\anaconda3\lib\site-packages (from sqlalchemy->pandasql) (4.15.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (pyproject.toml): started
  Building wheel for pandasql (pyproject.toml): finished with status 'done'
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26894 sha256=4e0910d229273170b74b2b89e9d84696f74213511b3dfa0a81f753eda4bad650
  Stored in directory: c:\users\kike2\appdata\local\pip\cache\wheels\b4\d0\8c\a6b366870bf041849cd96e03b71641e082f8d6456269b603b7
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [31]:
from pandasql import sqldf

query = """
SELECT department, COUNT(*) AS num_employees
FROM employees
WHERE department IN ('Computers', 'Beauty', 'Games')
GROUP BY department;
"""

result = sqldf(query, locals())
print(result)

  department  num_employees
0     Beauty             45
1  Computers             47
2      Games             36

In [34]:
regions.head()

   region_id     region        country
0          1  Southwest  United States
1          2  Northeast  United States
2          3  Northwest  United States
3          4    Central           Asia
4          5  East Asia           Asia

In [35]:
employees.head()

,employee_id,first_name,last_name,email,hire_date,department,gender,salary,region_id
0,1,Berrie,Manueau,berr@aol.com.mx,2006-04-20,Sports,F,154864,4
1,2,Aeriell,McNee,aeri@gmail.co,2009-01-26,Tools,F,56752,3
2,3,Sydney,Symonds,sydn@terra.mx,2010-05-17,Clothing,F,95313,4
3,4,Avrom,Rowantree,avro@terra.mx,2014-08-02,Phones & Tablets,M,119674,7
4,5,Fraiser,Morffew,feli@yahoo.com.mx,2003-01-14,Computers,M,55307,5

In [36]:
departments.head()

  department     division
0   Clothing         Home
1    Grocery         Home
2      Decor         Home
3  Furniture         Home
4  Computers  Electronics

In [40]:
query2 = """
SELECT e.first_name, e.last_name, d.division, r.region, r.country
FROM employees e
JOIN departments d ON e.department = d.department
JOIN regions r ON e.region_id = r.region_id;
"""
result2 = sqldf(query2, locals())
print(result2)

    first_name   last_name       division       region        country
0       Berrie     Manueau       Outdoors      Central           Asia
1      Aeriell       McNee       Hardware    Northwest  United States
2       Sydney     Symonds           Home      Central           Asia
3        Avrom   Rowantree    Electronics  Nova Scotia         Canada
4      Fraiser     Morffew    Electronics    East Asia           Asia
..         ...         ...            ...          ...            ...
938   Gardiner        Aron       Outdoors    Southwest  United States
939    Rhianna      Trynor        Fashion  Nova Scotia         Canada
940   Brandice  Gillicuddy    Electronics    Northeast  United States
941   Kingston      Piwall  Entertainment  Nova Scotia         Canada
942  Jacquelin      Cassam  Entertainment    Northeast  United States

[943 rows x 5 columns]