In [1]:
import pandas as pd, numpy as np

In [2]:
from functools import reduce

1. Utilizando una función Lambda se escribe un programa que eleve al cubo cada número de una lista de enteros.

In [3]:
numeros = range(1,27)
numeros_al_cubo = list(map(lambda x: x ** 3, numeros))
numeros_al_cubo

[1,
 8,
 27,
 64,
 125,
 216,
 343,
 512,
 729,
 1000,
 1331,
 1728,
 2197,
 2744,
 3375,
 4096,
 4913,
 5832,
 6859,
 8000,
 9261,
 10648,
 12167,
 13824,
 15625,
 17576]

2. Escribiendo un código que encuentre los elementos de longitud 6 de una lista utilizando una función ` lambda` e imprimiendo dichos elementos.

In [4]:
frutas = ["manzana", "durazno","mango","pera","maracuya","cereza","coco",
                  "platano", "fresa", "mandarina", "sandia", "naranja", "uva", "papaya"]

palabras_longitud_seis = list(filter(lambda palabra: len(palabra) == 6, frutas))

palabras_longitud_seis

['cereza', 'sandia', 'papaya']

3. Escribiendo un programa que `filtre` los números divisibles entre 11 de una lista dada.

In [5]:
numeros2 = range(1,1111,3)

divisibles_entre_11 = list(filter(lambda x: x % 11 == 0, numeros2))

divisibles_entre_11

[22,
 55,
 88,
 121,
 154,
 187,
 220,
 253,
 286,
 319,
 352,
 385,
 418,
 451,
 484,
 517,
 550,
 583,
 616,
 649,
 682,
 715,
 748,
 781,
 814,
 847,
 880,
 913,
 946,
 979,
 1012,
 1045,
 1078]

4. El `factorial` de un entero no negativo **n**, denotado por **n!**,  se define como el producto *n!* =  *1x 2 x 3 x...x (n-1) x n*. Por ejemplo: *4! = 1 x 2 x 3 x 4 = 24*.  Se escribe un programa que calcule el `factorial` de un número entre 0 y 30.

In [6]:
def factorial(n):
  if n < 0 or n > 30:
    raise ValueError("El número debe estar entre 0 y 30")
  if n == 0:
    return 1
  else:
    return reduce(lambda x, y: x * y, range(1, n + 1))

In [7]:
print("Escribe un número entre 0 y 30: ")
n = int(input())
print(f"El factorial de {n} es: {factorial(n)}")

Escribe un número entre 0 y 30:

 23

El factorial de 23 es: 25852016738884976640000

## Utilizando el archivo ` 'jamesbond_e.csv'` :

In [8]:
df = pd.read_csv('jamesbond_e.csv')
df.head()

,Year,Movie,Bond Actor,Director,Depicted Film Loc,Bond Car,Bond_Girl_Nat,US_Gross,World Gross,Budget,Film_Length,Avg_User_IMDB,Avg_User_Rtn_Tom
0,1962,Dr. No,Sean Connery,Terence Young,"Great Britain, Jamaic",Sunbeam,"Swiss, English, English",16067035,59567035,1000,110,7.3,7.7
1,1963,From Russia with Love,Sean Connery,Terence Young,"United Kingdom, Great Britain, Turkey, Croatia...",Bently,"English, Italian, English, Israeli",24800000,78900000,2000,115,7.5,8.0
2,1964,Goldfinger,Sean Connery,Guy Hamilton,"United States, Great Britain, Switzerland",Aston Martin,"Serbian, English",51100000,124900000,3000,110,7.8,8.4
3,1965,Thunderball,Sean Connery,Terence Young,"France, Great Britain, Bahamas, United States",Aston Martin,"French, Italian, Bahamian",63600000,141200000,9000,130,7.0,6.8
4,1967,You Only Live Twice,Sean Connery,Lewis Gilbert,"United States, Russia, Kazakhstan, Norway, Japan",Toyota,"Japanese, Chinese, German",43100000,111600000,9500,117,6.9,6.3

Comentarios útiles sobre algunas variables de este dataset:

   1. `Bond Actor` trae el nombre del actor.
   2. `World Gross` representa los ingresos que obtuvo la película a nivel mundial
   3. `Budget` es el presupuesto (en miles) destinado para cada película.
   4. `Avg_User_IMDB` y `Avg_User_Rtn_Tom` son calificaciones o ratings de las películas.

5. Obteniendo estadísticos descriptivos (conteo, media, desv estándar, min, max y cuartiles) de la variable 'World Gross'.

In [9]:
df['World Gross'].describe()

count    2.400000e+01
mean     2.882462e+08
std      2.657106e+08
min      5.956704e+07
25%      1.226750e+08
50%      1.864500e+08
75%      3.577551e+08
max      1.108561e+09
Name: World Gross, dtype: float64

6.  **a)** Haciendo que la variable 'Movie' sea el índice de la tabla y que este cambio sea `permanente`.    

    **b)** Escribiendo una instrucción para deshacer la operación anterior de forma `permanente` .

In [10]:
# a)
df = df.set_index('Movie', drop=True)

# b)
df = df.reset_index()

7. Utilizando `.loc[ ]`  para cambiar el nombre del actor de la siguiente forma: Siempre que el valor de la columna 'Bond Actor' sea igual a 'Daniel Craig', sustituirlo por 'Daniel Wroughton Craig'.

In [11]:
df.loc[df['Bond Actor'] == 'Daniel Craig', 'Bond Actor'] = 'Daniel Wroughton Craig'

8.  Calculando la media (promedio) de cada una de las variables 'Avg_User_IMDB'  y 'Avg_User_Rtn_Tom' y guarda estos valores en mean_1 y mean_2, respectivamente.

    **a)** Escribiendo una función llamada `califica( )` que reciba como argumento un `renglón` y califique a la película de  la siguiente manera:
    
    Si el actor es ` 'Roger Moore'`  o `'Daniel Craig'`   y además se cumple que  `Avg_User_IMDB > mean_1 `      Y  `Avg_User_Rtn_Tom > mean_2` , entonces regrese 'excelente' , de lo contrario que regrese 'buena'.

    **b)** Utilizando el método `apply( )`  para aplicar la función `califica()`  a cada uno de los renglones del data set.

In [12]:
mean_1 = df['Avg_User_IMDB'].mean()
mean_2 = df['Avg_User_Rtn_Tom'].mean()

# a)
def califica(row):
    if (row['Bond Actor'] == 'Roger Moore' or row['Bond Actor'] == 'Daniel Wroughton Craig') and row['Avg_User_IMDB'] > mean_1 and row['Avg_User_Rtn_Tom'] > mean_2:
        return 'excelente'
    else:
        return 'buena'

# b)
df['Calificacion'] = df.apply(califica, axis=1)

In [13]:
df['Calificacion'] = df.apply(califica, axis=1)
df

,Movie,Year,Bond Actor,Director,Depicted Film Loc,Bond Car,Bond_Girl_Nat,US_Gross,World Gross,Budget,Film_Length,Avg_User_IMDB,Avg_User_Rtn_Tom,Calificacion
0,Dr. No,1962,Sean Connery,Terence Young,"Great Britain, Jamaic",Sunbeam,"Swiss, English, English",16067035,59567035,1000,110,7.3,7.7,buena
1,From Russia with Love,1963,Sean Connery,Terence Young,"United Kingdom, Great Britain, Turkey, Croatia...",Bently,"English, Italian, English, Israeli",24800000,78900000,2000,115,7.5,8.0,buena
2,Goldfinger,1964,Sean Connery,Guy Hamilton,"United States, Great Britain, Switzerland",Aston Martin,"Serbian, English",51100000,124900000,3000,110,7.8,8.4,buena
3,Thunderball,1965,Sean Connery,Terence Young,"France, Great Britain, Bahamas, United States",Aston Martin,"French, Italian, Bahamian",63600000,141200000,9000,130,7.0,6.8,buena
4,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,"United States, Russia, Kazakhstan, Norway, Japan",Toyota,"Japanese, Chinese, German",43100000,111600000,9500,117,6.9,6.3,buena
5,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,"Portugal, Great Britain, Switzerland",Mercury,"English, English, Hungarian",22800000,82000000,8000,142,6.8,6.7,buena
6,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,"Japan, Egypt, France, South Africa, Great Brit...",Ford,American,43800000,116000000,7200,120,6.7,6.3,buena
7,Live and Let Die,1973,Roger Moore,Guy Hamilton,"United States, Great Britain, Jamaica",AMC,"English, American, English",35400000,161800000,7000,121,6.8,5.9,buena
8,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,"Great Britain, Lebanon, Portugal, Thailand",AMC,"Sweedish, French",21000000,97600000,7000,125,6.7,5.1,buena
9,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,"Austria, Russia, Great Britain, Egypt, Italy",Lotus,"American, English, Bosnian",46800000,185400000,14000,125,7.1,6.8,excelente
10,Moonraker,1979,Roger Moore,Lewis Gilbert,"Great Britain, United States, Italy, Brazil, R...",Lotus,"American, French, Moroccan",70300000,210300000,31000,126,6.2,5.7,buena
11,For Your Eyes Only,1981,Roger Moore,John Glen,"Great Britain, Russia, Spain, Italy, Greece, A...",Citroën,"French, Australian",54800000,195300000,28000,127,6.8,6.3,buena
12,Octopussy,1983,Roger Moore,John Glen,"Great Britain, India, Russia, Germany",Bajaj,"Sweedish, English",67900000,187500000,27500,131,6.5,5.3,buena
13,A View to a Kill,1985,Roger Moore,John Glen,"Russia, Great Britain, France, United States",Rolls Royce,"American, Jamaican, Sweedish, Nigerian",50327960,152627960,30000,131,6.2,4.7,buena
14,The Living Daylights,1987,Timothy Dalton,John Glen,"Gibraltar, Great Britain, Slovakia, Austria, M...",Rolls Royce,"Dutch, American",51185000,191200000,40000,130,6.7,6.3,buena
15,License to Kill,1989,Timothy Dalton,John Glen,"United States, Bahamas, Great Britain",Aston Martin,"American, American",34667015,156167015,42000,133,6.5,6.0,buena
16,GoldenEye,1995,Pierce Brosnan,Martin Campbell,"Russia, Monaco, France, England, United States...",BMW,"Polish, Dutch",106429941,356429941,60000,130,7.2,6.9,buena
17,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,"Russia, England, Germany, Vietnam",Aston Martin,"Malaysian, American, Danish",125304276,339504276,110000,119,6.4,6.0,buena
18,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,"Spain, England, Scotland, Kazakhstan, Azerbaij...",BMW,"American, French, English",126930660,361730660,135000,128,6.3,5.7,buena
19,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,"South Korea, Hong Kong, Cube, England, Iceland",Aston Martin,"American, Filipino",160942139,431942139,142000,133,6.0,6.1,buena
20,Casino Royale,2006,Daniel Wroughton Craig,Martin Campbell,"Czech Republic, Pakistan, Uganda, Madagascar, ...",Aston Martin,"French, Italian",167365000,596365000,102000,144,7.9,7.8,excelente
21,Quantum of Solace,2008,Daniel Wroughton Craig,Marc Forster,"Italy, England, Haiti, Austria, Bolivia, Russia",Aston Martin,English,169368427,591692078,230000,106,6.7,6.1,buena
22,Skyfall,2012,Daniel Wroughton Craig,Sam Mendes,"Turkey, England, China, Macau, Japan, Scotland",Aston Martin,"French, Greek, English",304360277,1108561108,200000,143,7.8,8.2,excelente
23,Spectre,2015,Daniel Wroughton Craig,Sam Mendes,"Mexico, England, Italy, Austria, Morocco, Vati...",Aston Martin,"French, Italian, Mexican",200074175,879620923,245000,148,6.8,6.4,buena