In [1]:
#Test de la Chi-Cuadrado

import pandas as pd
import numpy as np 
df = pd.read_csv('datos_abiertos_covid19.csv',nrows=1000)

In [2]:
np.random.seed(0)
df = df[df['ENTIDAD_UM'].isin(['25','27'])]
df = df.sample(frac=1)
df = df[0:800]

In [5]:
df['Suceptible'] = df['CARDIOVASCULAR'] == 2
observados = pd.crosstab(index=df['Suceptible'],columns=df['ENTIDAD_UM'], margins=True)

In [6]:
observados

ENTIDAD_UM  25   27  All
Suceptible
False        4    1    5
True        68  110  178
All         72  111  183

In [7]:
from scipy.stats import chi2_contingency

In [8]:
test = chi2_contingency(observados)

In [9]:
test

(3.5603401153962952,
 0.46876300408578,
 4,
 array([[  1.96721311,   3.03278689,   5.        ],
        [ 70.03278689, 107.96721311, 178.        ],
        [ 72.        , 111.        , 183.        ]]))

In [13]:
esperados = pd.DataFrame(test[3])

In [14]:
esperados

           0           1      2
0   1.967213    3.032787    5.0
1  70.032787  107.967213  178.0
2  72.000000  111.000000  183.0

In [15]:
esperados_rel = round(esperados.apply(lambda r: r/len(df) *100,axis=1),2)

In [16]:
observados_rel = round(observados.apply(lambda r: r/len(df) *100,axis=1),2)

In [17]:
observados_rel

ENTIDAD_UM     25     27     All
Suceptible
False        2.19   0.55    2.73
True        37.16  60.11   97.27
All         39.34  60.66  100.00

In [18]:
esperados_rel

       0      1       2
0   1.07   1.66    2.73
1  38.27  59.00   97.27
2  39.34  60.66  100.00

In [19]:
test[1]

0.46876300408578