In [1]:
import pandas as pd
import numpy as np 
df = pd.read_csv('datos_abiertos_covid19.csv', nrows = 6200)

In [2]:
df.head()

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,RESULTADO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,2020-07-30,004228,2,3,25,2,25,25,6,1,...,2,2,2,1,1,1,99,México,99,97
1,2020-07-30,1e6804,2,4,27,1,27,27,4,1,...,2,2,2,2,99,1,99,México,99,97
2,2020-07-30,105b61,2,4,15,2,15,15,9,1,...,2,1,2,2,99,1,99,México,99,97
3,2020-07-30,093267,2,4,2,2,2,2,4,2,...,2,1,2,2,99,1,99,México,99,2
4,2020-07-30,008cc5,2,3,25,2,25,25,18,2,...,2,2,2,2,2,1,99,México,99,2

In [3]:
np.corrcoef([df['OBESIDAD'],df['SEXO'],df['TABAQUISMO']])

array([[1.        , 0.00545513, 0.92072609],
       [0.00545513, 1.        , 0.00382255],
       [0.92072609, 0.00382255, 1.        ]])

In [4]:
df.drop(inplace = True, columns = ['FECHA_ACTUALIZACION','ID_REGISTRO','PAIS_NACIONALIDAD'])

In [5]:
df.corr()

,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,INTUBADO,NEUMONIA,...,OTRA_COM,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,RESULTADO,MIGRANTE,PAIS_ORIGEN,UCI
ORIGEN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SECTOR,NaN,1.000000,0.009647,-0.004301,0.010320,0.009830,0.062934,-0.031262,0.031157,0.014248,...,0.002852,0.000370,0.002314,0.002255,0.001788,0.010366,NaN,-0.005839,NaN,0.031186
ENTIDAD_UM,NaN,0.009647,1.000000,0.019226,0.775415,0.970991,0.354145,-0.030573,0.030990,0.076067,...,-0.002108,0.010032,-0.007920,-0.001160,0.002943,-0.065396,NaN,0.000573,NaN,0.030989
SEXO,NaN,-0.004301,0.019226,1.000000,0.014999,0.020784,-0.001770,0.123720,-0.124159,-0.105715,...,0.014605,0.008333,0.005455,0.009345,0.003823,-0.002557,NaN,-0.011849,NaN,-0.124086
ENTIDAD_NAC,NaN,0.010320,0.775415,0.014999,1.000000,0.775611,0.265558,-0.005746,0.006114,0.028985,...,0.017330,0.028732,0.015352,0.020028,0.023127,-0.052579,NaN,-0.124744,NaN,0.006112
ENTIDAD_RES,NaN,0.009830,0.970991,0.020784,0.775611,1.000000,0.377383,-0.032112,0.032522,0.067683,...,0.001088,0.013156,-0.004382,0.002362,0.006176,-0.068157,NaN,0.000977,NaN,0.032528
MUNICIPIO_RES,NaN,0.062934,0.354145,-0.001770,0.265558,0.377383,1.000000,-0.000250,-0.000012,0.046546,...,0.004312,0.003937,0.004806,0.004876,0.007740,0.054356,NaN,0.001702,NaN,0.000038
TIPO_PACIENTE,NaN,-0.031262,-0.030573,0.123720,-0.005746,-0.032112,-0.000250,1.000000,-0.999619,-0.531351,...,0.019475,0.022707,0.011334,0.019517,0.022085,0.034968,NaN,0.009008,NaN,-0.999621
INTUBADO,NaN,0.031157,0.030990,-0.124159,0.006114,0.032522,-0.000012,-0.999619,1.000000,0.531803,...,-0.019613,-0.022843,-0.011556,-0.019663,-0.022223,-0.035937,NaN,-0.009005,NaN,0.999996
NEUMONIA,NaN,0.014248,0.076067,-0.105715,0.028985,0.067683,0.046546,-0.531351,0.531803,1.000000,...,-0.005939,-0.009298,-0.007224,-0.005153,-0.005234,0.024766,NaN,-0.006780,NaN,0.531654
EDAD,NaN,-0.022224,0.008509,0.084741,0.032366,0.007094,0.022248,0.450883,-0.451037,-0.355837,...,0.005803,0.005872,0.000261,0.001362,0.002912,-0.010339,NaN,-0.017404,NaN,-0.450905
NACIONALIDAD,NaN,0.001012,-0.017319,-0.001766,0.249549,-0.018339,-0.010407,-0.004559,0.004556,0.013564,...,-0.002298,-0.001161,0.000144,-0.001068,-0.002140,-0.015365,NaN,-0.499879,NaN,0.004554
EMBARAZO,NaN,-0.004482,0.019800,0.998344,0.015167,0.021320,-0.000645,0.122569,-0.123009,-0.104912,...,0.014552,0.008266,0.005392,0.009283,0.003781,-0.002109,NaN,-0.011829,NaN,-0.122935
HABLA_LENGUA_INDIG,NaN,0.001215,-0.004894,0.027774,0.010718,-0.007145,-0.033728,-0.020015,0.019953,-0.001772,...,-0.002577,0.042622,-0.001764,-0.004426,-0.004563,-0.216168,NaN,0.000876,NaN,0.020000
DIABETES,NaN,0.001715,0.004466,0.016587,0.021137,0.007884,0.000041,0.002771,-0.002960,-0.003468,...,0.873210,0.845556,0.834394,0.904669,0.903436,-0.029044,NaN,0.000238,NaN,-0.002903
EPOC,NaN,0.000932,0.000325,0.010284,0.020875,0.003809,0.006241,0.021516,-0.021661,-0.005988,...,0.964499,0.934467,0.921446,0.999012,0.997909,-0.035633,NaN,0.000550,NaN,-0.021597
ASMA,NaN,0.000819,0.000510,0.016953,0.019351,0.003696,0.003682,0.025885,-0.026021,-0.012260,...,0.901316,0.873795,0.861189,0.934171,0.933092,-0.031695,NaN,0.000569,NaN,-0.025962
INMUSUPR,NaN,0.001269,-0.000103,0.010383,0.020608,0.003352,0.006075,0.022341,-0.022485,-0.006415,...,0.964696,0.933825,0.921423,0.999122,0.997825,-0.035446,NaN,0.000559,NaN,-0.022422
HIPERTENSION,NaN,0.003530,-0.002572,0.008091,0.017237,0.000622,0.005228,0.001697,-0.001820,0.007555,...,0.961106,0.931544,0.919244,0.995812,0.994225,-0.034968,NaN,-0.000036,NaN,-0.001761
OTRA_COM,NaN,0.002852,-0.002108,0.014605,0.017330,0.001088,0.004312,0.019475,-0.019613,-0.005939,...,1.000000,0.902098,0.888784,0.964378,0.963267,-0.046780,NaN,0.000477,NaN,-0.019551
CARDIOVASCULAR,NaN,0.000370,0.010032,0.008333,0.028732,0.013156,0.003937,0.022707,-0.022843,-0.009298,...,0.902098,1.000000,0.862021,0.934377,0.933279,-0.042670,NaN,0.000580,NaN,-0.022782
OBESIDAD,NaN,0.002314,-0.007920,0.005455,0.015352,-0.004382,0.004806,0.011334,-0.011556,-0.007224,...,0.888784,0.862021,1.000000,0.921205,0.920726,-0.040446,NaN,-0.000072,NaN,-0.011486
RENAL_CRONICA,NaN,0.002255,-0.001160,0.009345,0.020028,0.002362,0.004876,0.019517,-0.019663,-0.005153,...,0.964378,0.934377,0.921205,1.000000,0.997679,-0.034600,NaN,0.000534,NaN,-0.019597
TABAQUISMO,NaN,0.001788,0.002943,0.003823,0.023127,0.006176,0.007740,0.022085,-0.022223,-0.005234,...,0.963267,0.933279,0.920726,0.997679,1.000000,-0.035049,NaN,0.000375,NaN,-0.022158
OTRO_CASO,NaN,0.010366,-0.065396,-0.002557,-0.052579,-0.068157,0.054356,0.034968,-0.035937,0.024766,...,-0.046780,-0.042670,-0.040446,-0.034600,-0.035049,1.000000,NaN,0.042131,NaN,-0.035971
RESULTADO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MIGRANTE,NaN,-0.005839,0.000573,-0.011849,-0.124744,0.000977,0.001702,0.009008,-0.009005,-0.006780,...,0.000477,0.000580,-0.000072,0.000534,0.000375,0.042131,NaN,1.000000,NaN,-0.009005
PAIS_ORIGEN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UCI,NaN,0.031186,0.030989,-0.124086,0.006112,0.032528,0.000038,-0.999621,0.999996,0.531654,...,-0.019551,-0.022782,-0.011486,-0.019597,-0.022158,-0.035971,NaN,-0.009005,NaN,1.000000

In [6]:
df.drop(inplace = True, columns = ['RESULTADO','ORIGEN','MIGRANTE','PAIS_ORIGEN'])
corr = round(df.corr(),3)
corr.style.background_gradient()